### ISSUE TITLE
create_mask_model是否拼接了其他特征？

### ISSUE THREAD

**Issue by zysNLP** [zzhao1998/nq_model#1]
注意到您在cnq_model/bert_joint/create_model.py的create_mask_model函数这里提取了bert最后隐藏层的每个维度，然后做了两个concat，请问下48行的padding指的是普通的特征么？我看有11个，然后被您拼接到bert嵌入后面去了。我是否可以理解为除了使用bert本身提取特征的能力，您还在这里手动提取了11个特征，然后加到了bert里一起训练？

**Comment by zzhao1998** [comment]
这个项目是为了在阅读理解中回答不确定区间个数的答案提取问题的，我设计了两种思路，一种是直接预测每一个位置的概率（对应create_basic_model）然后在让模型学习一个动态的阈值去选择 ,还有一种我希望模型做多步预测，即每一次在已经预测出的答案的基础上去预测下一个答案（对应于create_mask_model），这种方法最后因为课程时间所限，我最后并没有做完，这种方法的话我需要在每一步输入已经预测出的答案的位置（mask_positions），这里的padding没有意义只是为了调整矩阵维度。
如果你需要做multi-spans extraction可以参考《A Multi-Type Multi-Span Network for Reading Comprehension that Requires Discrete Reasoning》这里也提供了一种类似的方法，效果还不错

**Comment by zysNLP** [comment]
感谢您的回答，我看了这篇论文，但似乎也并不是像我在issue中想要的，最近我就想在bert中加入使用传统特征，例如一篇阅读理解文章中，我手工制作了名词数量、动词数量、甚至各种单词的性质等这种显而易见的特征，我知道可以在原bert代码的create_model函数那里对output进行concat，但具体怎么做还是有点模糊，所以找到了你这里，我是对你这里的concat做法很感兴趣，觉得似乎可以参考来做，不知道你有没有什么建议的方法，我就是想要和你51行类似的shape=[batch_size, seq_length, hidden_size + 12]，这里我的12就是12个新的手工特征，但是就是不知道在bert源代码里其他地方怎么改，我的这些特征在什么时候什么地方加。。。

**Comment by zzhao1998** [comment]
我也没有在bert中加，这个相当于在bert之后接一个transformer，然后在这两个连接处加

**Comment by zzhao1998** [comment]
我想你的意思是在bert中的某一层添加吗？你可以找到bert内部中的transformer,中间的某一层像我这样插入一些特征就可以（我刚刚粗略的看了一下bert/modeling 205行），但是这样的话bert可能需要重新训练而不仅仅是finetune，我建议你可以先像我的做法一样（最后加一个transformer中间插），先试一下你的想法，这样成本会比较低，特别是我感觉bert说不定已经能自己找到你所说的这些特征。
另外我的代码这一段我没有跑过，不知道是不是对的。。。。。。

**Comment by zysNLP** [comment]
重新训练肯定是不可能了，我试试你说的方法，谢谢！～

**Comment by zysNLP** [comment]
最后问下老哥你的
mask_positions_matrix = tf.cast(tf.reshape(mask_positions, [batch_size * seq_length, 1]),dtype = tf.float32)
和padding = tf.zeros([batch_size * seq_length, 11], dtype=tf.float32)
这里的1和11各指的什么，1步预测？11步么？

**Comment by zzhao1998** [comment]
这个应该是为了凑12层，只有mask是有用的，padding是没用的，这个11是为了满足它12层的要求好像，这个12层好像是因为transformer的限制，具体好久以前记不太清了

**Comment by zysNLP** [comment]
你这里也没给出bert中你增加了很多create_attention_mask_from_input_mask、transformer_model的modeling，from bert import 这里没有公开代码，哈哈

**Comment by zysNLP** [comment]
bert确实有捕捉特征的能力，可能我也是多此一举，但有些任务上准确率等指标提不上去，只能另辟蹊径哈

**Comment by zzhao1998** [comment]
哈？我没有改原来的bert啊。。。。

**Comment by zysNLP** [comment]
你的create_model.py里第5行from bert import modeling是咋回事？

**Comment by zzhao1998** [comment]
这个用的就是原版的bert啊，https://github.com/google-research/bert

**Comment by zysNLP** [comment]
看见了。。。我的。
